title: TTNRT Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: /
theme: statustt-custom
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: East Proxy
      category: US East
      description: Proxy server for US East
    - name: Midwest Proxy
      category: US Midwest
      description: Proxy server for US Midwest
    - name: Mastodon
      category: US East
      link: https://social.ttnrtsite.me
      description: Social network
    - name: TTGit
      category: US East
      link: https://git.ttnrtsite.me
      description: Hosting your code!
    - name: CDN
      category: US East
      link: https://cdn.ttnrtsite.me
      description: Content Delivery Network
    - name: TTWeb
      category: US East
      link: https://www.ttnrtsite.me
      description: Our default website
    - name: STVRadio
      category: Other Services
      description: Listening to music
    - name: AssistAI
      category: Other Services
      description: Use AI on Discord!
      link: https://assist.ttnrtsite.me
    - name: TTGuard
      category: Other Services
      description: Guard your Discord server!
    - name: TTCloud
      category: US Midwest
      description: Sharing files made easier
      link: https://cloud.ttnrtsite.me
    - name: Meli
      category: US East
      description: Host your static sites
      link: https://ttnrtsite.io
    - name: API
      category: US Midwest
      description: Used for accessing the TTNRT API
      link: https://api.ttnrtsite.me/
    - name: IRC
      category: US East
      link: https://matrix.ttnrtsite.me
      description: Our IRC chatting site!
    - name: TTVerify
      category: Other Services
      link: https://verify.ttnrtsite.me
      description: A bot to verify you.
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: US East
      description: The main site in South Carolina
      closed: false
    - name: Other Services
      description: Separate services we have hosted
      closed: true
    - name: US Midwest
      description: The second site in Michigan
      closed: false
  description: Check for any outages or issues here!
  enableCustomHTML: true
  useLargeHeaderDesign: false
enableCustomHTML: true
